import Head from 'next/head'
import Navbar from '../components/Navbar'
import Section from '../components/Section'

export default function Home() {
  return (
  <div>
     <Head>
        <title>Skin laundry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/noTextT.png"/>
      </Head>
      <Navbar/>
      <Section/>
   </div>
  )
}
